### PR TITLE
Updates package version.

### PR DESCRIPTION
**Pull request by MicahZoltu**
This is in preparation for publishing a new version to NPM.

### CODE REVIEW

**Comment by MicahZoltu** [comment]
I don't think I have an NPM account, so I can't actually do the publish step.  :/

**Comment by nfroidure** [comment]
@MicahZoltu you can create one, it's free ;). Otherwise, i'll do it when i'll have some time to.

**Comment by nfroidure** [comment]
Btw, did you use `npm version patch`? It is not required but doing so will create a release tag for you. Also, you will have to `git push --tags` when done to actually send the newly created tag.

**Comment by MicahZoltu** [comment]
No, I just bumped the version in the file.  I ended up going another route with my problem, so I don't have a particularly high incentive to push this through to NPM at the moment.  Feel free to close.

**Pull request closed without merging**
